package com.assu.server.global.apiPayload.code.status;

import lombok.Getter;

import java.util.Set;

@Getter
public enum SwaggerErrorCodes {

    // ===== Admin / Auth =====
    ADMIN_PARTNER_RECOMMEND(Set.of(
            ErrorStatus.NO_SUCH_ADMIN,
            ErrorStatus.NO_AVAILABLE_PARTNER
    )),
    ADMIN_DASHBOARD_COUNT_ADMIN(Set.of(
            ErrorStatus.NO_SUCH_ADMIN
    )),
    ADMIN_DASHBOARD_NEW_STUDENT_COUNT(Set.of(
            ErrorStatus.NO_SUCH_ADMIN
    )),
    ADMIN_DASHBOARD_COUNT_USER(Set.of(
            ErrorStatus.NO_SUCH_ADMIN
    )),
    ADMIN_DASHBOARD_TOP_USAGE(Set.of(
            ErrorStatus.NO_SUCH_ADMIN,
            ErrorStatus.NO_USAGE_DATA,
            ErrorStatus.NO_PAPER_FOR_STORE
    )),
    ADMIN_DASHBOARD_USAGE_LIST(Set.of(
            ErrorStatus.NO_SUCH_ADMIN,
            ErrorStatus.NO_PAPER_FOR_STORE
    )),
    AUTH_PHONE_SEND_CODE(Set.of(
            ErrorStatus.EXISTED_PHONE,
            ErrorStatus.FAILED_TO_SEND_SMS,
            ErrorStatus.FAILED_TO_PARSE_ALIGO
    )),
    AUTH_PHONE_VERIFY_CODE(Set.of(
            ErrorStatus.NOT_VERIFIED_PHONE_NUMBER
    )),
    AUTH_EMAIL_CHECK(Set.of(
            ErrorStatus.EXISTED_EMAIL
    )),
    AUTH_SIGNUP_STUDENT(Set.of(
            ErrorStatus.SSU_SAINT_SSO_FAILED,
            ErrorStatus.SSU_SAINT_PORTAL_FAILED,
            ErrorStatus.SSU_SAINT_PARSE_FAILED,
            ErrorStatus.SSU_SAINT_UNSUPPORTED_MAJOR,
            ErrorStatus.EXISTED_STUDENT,
            ErrorStatus.AUTHORIZATION_EXCEPTION
    )),
    AUTH_SIGNUP_PARTNER(Set.of(
            ErrorStatus.NOT_VERIFIED_PHONE_NUMBER,
            ErrorStatus.EXISTED_PHONE,
            ErrorStatus._BAD_REQUEST,
            ErrorStatus.EXISTED_EMAIL,
            ErrorStatus.AUTHORIZATION_EXCEPTION
    )),
    AUTH_SIGNUP_ADMIN(Set.of(
            ErrorStatus.NOT_VERIFIED_PHONE_NUMBER,
            ErrorStatus.EXISTED_PHONE,
            ErrorStatus.EXISTED_EMAIL,
            ErrorStatus._BAD_REQUEST,
            ErrorStatus.AUTHORIZATION_EXCEPTION
    )),
    AUTH_LOGIN_COMMON(Set.of(
            ErrorStatus.MEMBER_PENDING_APPROVAL,
            ErrorStatus.BACKOFFICE_USE_DEDICATED_LOGIN,
            ErrorStatus.AUTHORIZATION_EXCEPTION
    )),
    AUTH_LOGIN_STUDENT(Set.of(
            ErrorStatus.SSU_SAINT_SSO_FAILED,
            ErrorStatus.SSU_SAINT_PORTAL_FAILED,
            ErrorStatus.SSU_SAINT_PARSE_FAILED,
            ErrorStatus.SSU_SAINT_UNSUPPORTED_MAJOR,
            ErrorStatus.AUTHORIZATION_EXCEPTION,
            ErrorStatus.NO_SUCH_MEMBER
    )),
    AUTH_TOKEN_REFRESH(Set.of(
            ErrorStatus.BACKOFFICE_USE_DEDICATED_LOGIN,
            ErrorStatus.JWT_REFRESH_TOKEN_EXPIRED,
            ErrorStatus.AUTHORIZATION_EXCEPTION,
            ErrorStatus.REFRESH_TOKEN_NOT_EQUAL
    )),
    AUTH_LOGOUT(Set.of(
            ErrorStatus.AUTHORIZATION_EXCEPTION
    )),
    AUTH_SSU_VERIFY(Set.of(
            ErrorStatus.SSU_SAINT_SSO_FAILED,
            ErrorStatus.SSU_SAINT_PORTAL_FAILED,
            ErrorStatus.SSU_SAINT_PARSE_FAILED,
            ErrorStatus.SSU_SAINT_UNSUPPORTED_MAJOR
    )),
    AUTH_WITHDRAW(Set.of(
            ErrorStatus.AUTHORIZATION_EXCEPTION,
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.MEMBER_ALREADY_WITHDRAWN
    )),
    BACKOFFICE_AUTH_LOGIN(Set.of(
            ErrorStatus.NO_BACKOFFICE_TYPE,
            ErrorStatus.AUTHORIZATION_EXCEPTION
    )),
    BACKOFFICE_AUTH_REFRESH(Set.of(
            ErrorStatus.JWT_AUDIENCE_MISMATCH,
            ErrorStatus.JWT_REFRESH_TOKEN_EXPIRED,
            ErrorStatus.AUTHORIZATION_EXCEPTION,
            ErrorStatus.REFRESH_TOKEN_NOT_EQUAL
    )),

    // ===== Backoffice: Admin/Member/Partner/Operator =====
    BACKOFFICE_ADMIN_GET_SIGN_IMAGE(Set.of(
            ErrorStatus.NO_SUCH_ADMIN,
            ErrorStatus.SIGN_IMAGE_NOT_FOUND
    )),
    BACKOFFICE_ADMIN_CREATE(Set.of(
            ErrorStatus.EXISTED_EMAIL,
            ErrorStatus.EXISTED_PHONE
    )),
    BACKOFFICE_ADMIN_UPDATE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.EXISTED_EMAIL,
            ErrorStatus.EXISTED_PHONE
    )),
    BACKOFFICE_ADMIN_DELETE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER
    )),
    BACKOFFICE_MEMBER_GET_DETAIL(Set.of(
            ErrorStatus.NO_SUCH_MEMBER
    )),
    BACKOFFICE_MEMBER_APPROVE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.MEMBER_APPROVAL_NOT_SUPPORTED,
            ErrorStatus.MEMBER_ALREADY_WITHDRAWN,
            ErrorStatus.MEMBER_NOT_PENDING_APPROVAL,
            ErrorStatus.PARTNER_STORE_NOT_FOUND
    )),
    BACKOFFICE_MEMBER_REJECT(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.MEMBER_APPROVAL_NOT_SUPPORTED,
            ErrorStatus.MEMBER_ALREADY_WITHDRAWN,
            ErrorStatus.MEMBER_NOT_PENDING_APPROVAL
    )),
    BACKOFFICE_MEMBER_FORCE_WITHDRAW(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.CANNOT_WITHDRAW_BACKOFFICE_MEMBER,
            ErrorStatus.MEMBER_ALREADY_WITHDRAWN
    )),
    BACKOFFICE_MEMBER_RESTORE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.MEMBER_NOT_DELETED
    )),
    BACKOFFICE_PARTNER_GET_LICENSE(Set.of(
            ErrorStatus.NO_SUCH_PARTNER,
            ErrorStatus.LICENSE_NOT_FOUND
    )),
    BACKOFFICE_PARTNER_VERIFY_LICENSE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.NO_SUCH_PARTNER,
            ErrorStatus.LICENSE_NOT_FOUND
    )),
    BACKOFFICE_PARTNER_UPDATE_PROFILE_IMAGE(Set.of(
            ErrorStatus.NO_SUCH_PARTNER,
            ErrorStatus.PROFILE_IMAGE_NOT_FOUND,
            ErrorStatus.FILE_SIZE_EXCEEDED,
            ErrorStatus.INVALID_FILE_NAME,
            ErrorStatus.INVALID_FILE_TYPE,
            ErrorStatus.INVALID_CONTENT_TYPE
    )),
    BACKOFFICE_PARTNER_DELETE_PROFILE_IMAGE(Set.of(
            ErrorStatus.NO_SUCH_PARTNER,
            ErrorStatus.PROFILE_IMAGE_NOT_FOUND,
            ErrorStatus.PROFILE_IMAGE_DELETE_FAILED
    )),
    BACKOFFICE_PARTNER_BATCH_SIGNUP(Set.of(
            ErrorStatus.EXISTED_EMAIL
    )),
    BACKOFFICE_OPERATOR_CREATE(Set.of(
            ErrorStatus.EXISTED_EMAIL
    )),

    // ===== Backoffice: Paper/Partnership/HomeCuration/Chat/Inquiry/Notification/Report/DevSync =====
    BACKOFFICE_PAPER_CREATE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER
    )),
    BACKOFFICE_PAPER_CONTENT_ADD(Set.of(
            ErrorStatus.NO_SUCH_MEMBER
    )),
    BACKOFFICE_PAPER_APPROVE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.ALREADY_APPROVED
    )),
    BACKOFFICE_PAPER_REJECT(Set.of(
            ErrorStatus.NO_SUCH_MEMBER
    )),
    BACKOFFICE_PAPER_EXPIRE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER
    )),
    BACKOFFICE_HOME_CURATION_UPDATE(Set.of(
            ErrorStatus._BAD_REQUEST,
            ErrorStatus.NO_SUCH_STORE
    )),
    BACKOFFICE_CHAT_BLOCK_BETWEEN(Set.of(
            ErrorStatus._BAD_REQUEST,
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.ALREADY_CHAT_BLOCKED
    )),
    BACKOFFICE_CHAT_UNBLOCK_BETWEEN(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.NOT_CHAT_BLOCKED
    )),
    BACKOFFICE_CHAT_BLOCK_MEMBER(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.ALREADY_CHAT_BLOCKED
    )),
    BACKOFFICE_CHAT_UNBLOCK_MEMBER(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.NOT_CHAT_BLOCKED
    )),
    BACKOFFICE_INQUIRY_LIST(Set.of(
            ErrorStatus.PAGE_UNDER_ONE,
            ErrorStatus.PAGE_SIZE_INVALID
    )),
    BACKOFFICE_INQUIRY_DETAIL(Set.of(
            ErrorStatus.NO_SUCH_INQUIRY
    )),
    BACKOFFICE_INQUIRY_ANSWER(Set.of(
            ErrorStatus.NO_SUCH_INQUIRY,
            ErrorStatus.ALREADY_ANSWERED
    )),
    BACKOFFICE_NOTIFICATION_PUSH_SEND(Set.of(
            ErrorStatus.RECEIVER_ID_REQUIRED,
            ErrorStatus.NO_SUCH_MEMBER
    )),
    BACKOFFICE_NOTIFICATION_PUSH_LOG_LIST(Set.of(
            ErrorStatus.PAGE_UNDER_ONE,
            ErrorStatus.PAGE_SIZE_INVALID
    )),
    BACKOFFICE_NOTIFICATION_OUTBOX_FAILED_LIST(Set.of(
            ErrorStatus.PAGE_UNDER_ONE,
            ErrorStatus.PAGE_SIZE_INVALID
    )),
    BACKOFFICE_NOTIFICATION_OUTBOX_RETRY(Set.of(
            ErrorStatus.OUTBOX_NOT_FOUND,
            ErrorStatus.OUTBOX_NOT_FAILED
    )),
    BACKOFFICE_REPORT_DETAIL(Set.of(
            ErrorStatus.NO_SUCH_REPORT
    )),
    BACKOFFICE_REPORT_STATUS_UPDATE(Set.of(
            ErrorStatus.NO_SUCH_REPORT,
            ErrorStatus._BAD_REQUEST
    )),
    BACKOFFICE_REPORT_REJECT(Set.of(
            ErrorStatus._BAD_REQUEST
    )),
    BACKOFFICE_REVIEW_DELETE(Set.of(
            ErrorStatus._BAD_REQUEST
    )),
    BACKOFFICE_SUGGESTION_DELETE(Set.of(
            ErrorStatus.NO_SUCH_SUGGESTION,
            ErrorStatus._BAD_REQUEST
    )),
    BACKOFFICE_DEV_SYNC(Set.of(
            ErrorStatus.INVALID_DEV_SYNC_TARGET,
            ErrorStatus._INTERNAL_SERVER_ERROR
    )),

    // ===== Certification / Chat / DeviceToken / Member / Notification =====
    CERTIFICATION_EXPIRE_SESSION(Set.of(
            ErrorStatus.NO_SUCH_SESSION,
            ErrorStatus._FORBIDDEN
    )),
    CERTIFICATION_PERSONAL(Set.of(
            ErrorStatus.NO_SUCH_STORE
    )),
    CHAT_CREATE_ROOM(Set.of(
            ErrorStatus.NO_SUCH_ADMIN,
            ErrorStatus.NO_SUCH_PARTNER,
            ErrorStatus.NO_SUCH_STORE,
            ErrorStatus.NO_SUCH_STORE_WITH_THAT_PARTNER
    )),
    CHAT_GET_HISTORY(Set.of(
            ErrorStatus.NO_SUCH_ROOM
    )),
    CHAT_LEAVE_ROOM(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.NO_MEMBER_IN_THE_ROOM,
            ErrorStatus.NO_MEMBER
    )),
    CHAT_BLOCK_MEMBER(Set.of(
            ErrorStatus._BAD_REQUEST
    )),
    CHAT_CHECK_BLOCK(Set.of(
            ErrorStatus._BAD_REQUEST
    )),
    CHAT_UNBLOCK_MEMBER(Set.of(
            ErrorStatus.NO_SUCH_MEMBER
    )),
    CHAT_GET_BLOCK_LIST(Set.of(
            ErrorStatus._BAD_REQUEST
    )),
    DEVICE_TOKEN_REGISTER(Set.of(
            ErrorStatus.NO_SUCH_MEMBER
    )),
    DEVICE_TOKEN_UNREGISTER(Set.of(
            ErrorStatus.DEVICE_TOKEN_NOT_OWNED,
            ErrorStatus.DEVICE_TOKEN_NOT_FOUND
    )),
    MEMBER_UPLOAD_PROFILE_IMAGE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.PROFILE_IMAGE_NOT_FOUND,
            ErrorStatus.FILE_SIZE_EXCEEDED,
            ErrorStatus.INVALID_FILE_NAME,
            ErrorStatus.INVALID_FILE_TYPE,
            ErrorStatus.INVALID_CONTENT_TYPE
    )),
    MEMBER_GET_PROFILE_IMAGE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.PROFILE_IMAGE_NOT_FOUND
    )),
    MEMBER_DELETE_PROFILE_IMAGE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.PROFILE_IMAGE_NOT_FOUND,
            ErrorStatus.PROFILE_IMAGE_DELETE_FAILED
    )),
    NOTIFICATION_LIST(Set.of(
            ErrorStatus.PAGE_UNDER_ONE,
            ErrorStatus.PAGE_SIZE_INVALID,
            ErrorStatus.NO_SUCH_MEMBER
    )),
    NOTIFICATION_MARK_READ(Set.of(
            ErrorStatus.NOTIFICATION_NOT_FOUND,
            ErrorStatus.NOTIFICATION_ACCESS_DENIED
    )),
    NOTIFICATION_QUEUE(Set.of(
            ErrorStatus.INVALID_NOTIFICATION_TYPE,
            ErrorStatus.MISSING_NOTIFICATION_FIELD,
            ErrorStatus.NO_SUCH_MEMBER
    )),
    NOTIFICATION_TOGGLE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER
    )),
    NOTIFICATION_GET_SETTINGS(Set.of(
            ErrorStatus.NO_SUCH_MEMBER
    )),

    // ===== Partner / QR / Report / Suggestion / Inquiry =====
    PARTNER_RANDOM_ADMIN_RECOMMEND(Set.of(
            ErrorStatus.NO_SUCH_PARTNER,
            ErrorStatus.NO_SUCH_ADMIN
    )),
    TEMPORARY_QR_INSERT_DATA(Set.of(
            ErrorStatus.NO_SUCH_STUDENT
    )),
    TEMPORARY_QR_GET_MY_DATA(Set.of(
            ErrorStatus.NO_SUCH_STUDENT
    )),
    REPORT_CREATE_CONTENT(Set.of(
            ErrorStatus.NO_MEMBER,
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.REVIEW_REPORT_SELF_NOT_ALLOWED,
            ErrorStatus.NO_SUCH_SUGGESTION,
            ErrorStatus.SUGGESTION_REPORT_SELF_NOT_ALLOWED,
            ErrorStatus.INVALID_REPORT_TYPE,
            ErrorStatus.REPORT_DUPLICATE
    )),
    REPORT_CREATE_STUDENT(Set.of(
            ErrorStatus.NO_MEMBER,
            ErrorStatus.NO_SUCH_MEMBER,
            ErrorStatus.NO_SUCH_SUGGESTION,
            ErrorStatus.INVALID_REPORT_TYPE,
            ErrorStatus.REPORT_SELF_NOT_ALLOWED,
            ErrorStatus.REPORT_DUPLICATE
    )),
    SUGGESTION_WRITE(Set.of(
            ErrorStatus.NO_SUCH_ADMIN,
            ErrorStatus.NO_SUCH_STUDENT
    )),
    SUGGESTION_GET_ADMINS(Set.of(
            ErrorStatus.NO_SUCH_STUDENT
    )),
    INQUIRY_CREATE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER
    )),
    INQUIRY_LIST(Set.of(
            ErrorStatus.PAGE_UNDER_ONE,
            ErrorStatus.PAGE_SIZE_INVALID
    )),
    INQUIRY_GET(Set.of(
            ErrorStatus.NO_SUCH_INQUIRY,
            ErrorStatus.FORBIDDEN_INQUIRY
    )),

    // ===== Partnership / Review / Student / Store / AppReview =====
    PARTNERSHIP_RECORD_USAGE(Set.of(
            ErrorStatus.NO_SUCH_CONTENT,
            ErrorStatus.NO_SUCH_STORE
    )),
    PARTNERSHIP_CREATE_DRAFT(Set.of(
            ErrorStatus.NO_SUCH_ADMIN,
            ErrorStatus.NO_SUCH_PARTNER,
            ErrorStatus.NO_SUCH_STORE
    )),
    PARTNERSHIP_CREATE_MANUAL(Set.of(
            ErrorStatus._BAD_REQUEST,
            ErrorStatus.NO_SUCH_ADMIN,
            ErrorStatus.IMAGE_UPLOAD_FAILED
    )),
    PARTNERSHIP_UPDATE(Set.of(
            ErrorStatus._BAD_REQUEST,
            ErrorStatus.NO_SUCH_PAPER
    )),
    PARTNERSHIP_UPDATE_STATUS(Set.of(
            ErrorStatus.NO_SUCH_PAPER,
            ErrorStatus._FORBIDDEN,
            ErrorStatus._BAD_REQUEST,
            ErrorStatus.NO_SUCH_ADMIN,
            ErrorStatus.NO_SUCH_PARTNER
    )),
    PARTNERSHIP_GET_DETAIL(Set.of(
            ErrorStatus.NO_SUCH_PAPER,
            ErrorStatus._FORBIDDEN
    )),
    PARTNERSHIP_DELETE(Set.of(
            ErrorStatus.NO_SUCH_PAPER,
            ErrorStatus._FORBIDDEN
    )),
    PARTNERSHIP_DELETE_SUSPENDED(Set.of(
            ErrorStatus.NO_SUCH_PAPER,
            ErrorStatus._FORBIDDEN,
            ErrorStatus._BAD_REQUEST
    )),
    PARTNERSHIP_CHECK_WITH_PARTNER(Set.of(
            ErrorStatus.NO_SUCH_PARTNER
    )),
    PARTNERSHIP_CHECK_WITH_ADMIN(Set.of(
            ErrorStatus.NO_SUCH_ADMIN
    )),
    REVIEW_WRITE(Set.of(
            ErrorStatus.NO_SUCH_STORE,
            ErrorStatus.NO_SUCH_PARTNER,
            ErrorStatus.NO_SUCH_STUDENT,
            ErrorStatus.IMAGE_UPLOAD_FAILED,
            ErrorStatus.NO_SUCH_USAGE
    )),
    REVIEW_CHECK_PARTNER(Set.of(
            ErrorStatus.NO_SUCH_PARTNER,
            ErrorStatus.NO_SUCH_STORE
    )),
    REVIEW_CHECK_STORE(Set.of(
            ErrorStatus.NO_SUCH_STORE
    )),
    REVIEW_DELETE(Set.of(
            ErrorStatus._BAD_REQUEST
    )),
    REVIEW_MY_STORE_AVERAGE(Set.of(
            ErrorStatus.NO_SUCH_PARTNER,
            ErrorStatus.NO_SUCH_STORE
    )),
    STUDENT_GET_STAMP(Set.of(
            ErrorStatus.NO_SUCH_STUDENT
    )),
    STUDENT_EARN_STAMP(Set.of(
            ErrorStatus.NO_SUCH_STUDENT
    )),
    STUDENT_GET_PROFILE(Set.of(
            ErrorStatus.NO_SUCH_STUDENT
    )),
    STUDENT_GET_HOME_CURATION(Set.of(
            ErrorStatus.NO_SUCH_STUDENT
    )),
    STORE_GET_DETAIL(Set.of(
            ErrorStatus.NO_SUCH_STORE
    )),
    STORE_GET_PAPER_CONTENT(Set.of(
            ErrorStatus.NO_STUDENT_TYPE,
            ErrorStatus.NO_SUCH_STORE
    )),
    STORE_GET_WEEKLY_RANK(Set.of(
            ErrorStatus.NO_SUCH_STORE
    )),
    STORE_GET_WEEKLY_RANK_LIST(Set.of(
            ErrorStatus.NO_SUCH_STORE
    )),
    APP_REVIEW_CREATE(Set.of(
            ErrorStatus.NO_SUCH_MEMBER
    ));

    private final Set<ErrorStatus> errorCodes;

    SwaggerErrorCodes(Set<ErrorStatus> errorCodes) {
        this.errorCodes = errorCodes;
    }
}
